name: Workflow d'initiation
on:
  push:
    paths:
      - 'docs/**'   

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Ca marche
  #       run: |
  #         echo "Ca marche !"
  #         # Add your actual script commands here