name: Workflow d'initiation
on:
  push:
    paths:
      - 'docs/**'   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lister les fichiers modifiés
        run: |
          echo "Fichiers modifiés par ce push :"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}