name: PR Check
on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: valeur-du-contexte
        run: |
          echo "La valeur du contexte est : ${{ github.actor }} - ${{ github.event_name }} - ${{ github.ref }}"
          # Add your actual script commands here
      

