name: PR Check
on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: valeur-du-contexte
        run: |
          echo "La valeur du contexte est : ${{ github.actor }}"
          # Add your actual script commands here
      
      - name: afficher-la-date 
        run: |
         curl -L \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/OWNER/REPO/pulls/PULL_NUMBER

